import { createRepoFromTemplate, updateFile, uploadBinaryFile, setRepoSecret, fetchFileContent } from '../tools/github.js'
import type { Lead, PipelineConfig, AgentResult } from '../types.js'
import type { HeroImages } from './image-generator.js'

// ─── Brand color CSS generator ────────────────────────────────────────────────
// Injects per-client brand colors as CSS variable overrides into globals.css.
// Scoped to [data-theme="<theme>"] so they take precedence over preset tokens.

const HEX6 = /^#[0-9A-Fa-f]{6}$/

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.slice(1), 16)
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255]
}

function rgbToHex(r: number, g: number, b: number): string {
  return '#' + [r, g, b].map(v => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('')
}

function darken(hex: string, factor: number): string {
  const [r, g, b] = hexToRgb(hex)
  return rgbToHex(r * factor, g * factor, b * factor)
}

function lighten(hex: string, factor: number): string {
  const [r, g, b] = hexToRgb(hex)
  return rgbToHex(r + (255 - r) * factor, g + (255 - g) * factor, b + (255 - b) * factor)
}

function hexToRgba(hex: string, alpha: number): string {
  const [r, g, b] = hexToRgb(hex)
  return `rgba(${r}, ${g}, ${b}, ${alpha})`
}

function generateBrandColorCSS(
  colors: { primary?: string; secondary?: string; accent?: string },
  theme: string
): string | null {
  const primary = colors.primary && HEX6.test(colors.primary) ? colors.primary : null
  const accent  = colors.accent  && HEX6.test(colors.accent)  ? colors.accent  : primary

  if (!primary && !accent) return null

  const base    = primary ?? accent!
  const hi      = accent  ?? primary!

  const lines = [
    `/* ── Client brand color override (generated by pipeline) ── */`,
    `[data-theme="${theme}"] {`,
    `  --brand-bg:           ${darken(base, 0.08)};`,
    `  --brand-bg-mid:       ${darken(base, 0.12)};`,
    `  --brand-bg-section:   ${darken(base, 0.10)};`,
    `  --brand-accent:       ${hi};`,
    `  --brand-accent-light: ${lighten(hi, 0.20)};`,
    `  --brand-accent-glow:  ${hexToRgba(hi, 0.40)};`,
    `  --brand-grad-from:    ${lighten(hi, 0.12)};`,
    `  --brand-grad-to:      ${hi};`,
    `  --brand-rule:         ${hi};`,
    `  --brand-blob-1:       ${hexToRgba(hi, 0.30)};`,
    `  --brand-blob-2:       ${hexToRgba(lighten(hi, 0.25), 0.20)};`,
    `  --brand-particle:     ${hi};`,
    `}`,
  ]

  return lines.join('\n')
}

// ─── Dynamic page.tsx generator ──────────────────────────────────────────────
// Generates a unique page.tsx when hero layout is HeroCentered or HeroBento.
// Falls back to existing template page.tsx for all other layouts.

interface NichePageConfig {
  localImports: string   // @/components/* imports
  nicheSection: string   // JSX for the niche-specific section
  contactHeading: string
  contactParagraph: string
  contactSubmit: string
  ctaJsx: string         // pre-formatted Reviews ctaText JSX literal
}

// Pre-formatted ctaText uses runtime config values — single-quoted to avoid TS template confusion
const NICHE_PAGE: Record<string, NichePageConfig> = {
  hvac: {
    localImports: `import BrandStorySection from "@/components/brand-story-section"`,
    nicheSection: `<BrandStorySection />`,
    contactHeading: 'Schedule Your Service',
    contactParagraph: 'Same-day slots available. Our team will confirm within 30 minutes.',
    contactSubmit: 'Schedule Service',
    ctaJsx: 'Join ${config.business.review_count}+ Happy Customers — Call Now',
  },
  roofing: {
    localImports: `import { MaterialsSection } from "@/components/materials-section"`,
    nicheSection: `<MaterialsSection config={config} />`,
    contactHeading: 'Get Your Free Roof Inspection',
    contactParagraph: 'Drone inspection + written report at no charge. Most insurance claims handled directly.',
    contactSubmit: 'Schedule Free Inspection',
    ctaJsx: 'Free roof inspection — ${config.business.review_count}+ roofs installed',
  },
  dentist: {
    localImports: `import { SmileGallerySection } from "@/components/smile-gallery"`,
    nicheSection: `<SmileGallerySection config={config} />`,
    contactHeading: 'Book Your Appointment',
    contactParagraph: 'New patients welcome. Most insurance accepted. Same-day emergency slots available.',
    contactSubmit: 'Request Appointment',
    ctaJsx: 'Book online — ${config.business.review_count}+ patients trust us',
  },
  medspa: {
    localImports: `import { TreatmentMenuSection } from "@/components/treatment-menu"`,
    nicheSection: `<TreatmentMenuSection config={config} />`,
    contactHeading: 'Book Your Consultation',
    contactParagraph: 'Every treatment plan starts with a complimentary consultation. No pressure — just results.',
    contactSubmit: 'Book Free Consultation',
    ctaJsx: 'Book your free consultation — ${config.business.review_count}+ happy clients',
  },
  lawfirm: {
    localImports: `import { PracticeAreasSection } from "@/components/practice-areas"\nimport { AttorneySection } from "@/components/attorney-section"`,
    nicheSection: `<PracticeAreasSection config={config} />\n        <AttorneySection config={config} />`,
    contactHeading: 'Get Your Free Case Evaluation',
    contactParagraph: 'Tell us what happened. Our attorneys review every submission and respond within 2 hours.',
    contactSubmit: 'Request Free Evaluation',
    ctaJsx: 'Free case evaluation — ${config.business.review_count}+ clients represented',
  },
  remodeling: {
    localImports: `import { ProjectGallerySection } from "@/components/project-gallery"`,
    nicheSection: `<ProjectGallerySection config={config} />`,
    contactHeading: 'Start Your Remodel',
    contactParagraph: 'Free consultation + 3D design preview. No obligation to proceed.',
    contactSubmit: 'Request Free Consult',
    ctaJsx: 'Free design consult — ${config.business.review_count}+ projects completed',
  },
  cleaning: {
    localImports: `import { GuaranteeSection } from "@/components/guarantee-section"`,
    nicheSection: `<GuaranteeSection config={config} />`,
    contactHeading: 'Book Your First Clean',
    contactParagraph: 'First-time clients get 10% off. Book online or call — takes 60 seconds.',
    contactSubmit: 'Schedule My Clean',
    ctaJsx: 'Join ${config.business.review_count}+ clean homes in ${config.business.city}',
  },
  'junk-removal': {
    localImports: `import { ProcessSection } from "@/components/process-section"`,
    nicheSection: `<ProcessSection config={config} />`,
    contactHeading: 'Get Your Upfront Quote',
    contactParagraph: "Tell us what you need gone. We'll give you a price before we touch anything.",
    contactSubmit: 'Get My Quote',
    ctaJsx: 'Same-day available — ${config.business.review_count}+ loads hauled',
  },
  daycare: {
    localImports: `import { CurriculumSection } from "@/components/curriculum-section"`,
    nicheSection: `<CurriculumSection config={config} />`,
    contactHeading: 'Schedule Your Tour',
    contactParagraph: 'Every family gets a personal walkthrough before enrollment. No pressure — just a conversation.',
    contactSubmit: 'Book a Tour',
    ctaJsx: 'Schedule a tour — ${config.business.review_count}+ families enrolled',
  },
  'auto-detailing': {
    localImports: `import { PackagesSection } from "@/components/packages-section"`,
    nicheSection: `<PackagesSection config={config} />`,
    contactHeading: 'Book Your Detail',
    contactParagraph: "Not sure which package? We'll inspect your paint and recommend for free.",
    contactSubmit: 'Book My Detail',
    ctaJsx: 'Book your detail — ${config.business.review_count}+ vehicles transformed',
  },
}

function generatePageTsx(niche: string, heroLayoutId: string): string | null {
  const pg = NICHE_PAGE[niche]
  if (!pg) return null

  const isCentered = heroLayoutId === 'centered-editorial'
  const isBento    = heroLayoutId === 'bento-hero'
  if (!isCentered && !isBento) return null

  const heroImport = isCentered ? 'HeroCentered' : 'HeroBento'
  const heroJsx    = isCentered
    ? `<HeroCentered config={config} posterSrc="/hero-1.jpg" />`
    : `<HeroBento config={config} photoSrc="/hero-1.jpg" />`

  // ctaJsx uses template literal syntax — single-quoted in our object, backtick-wrapped in output
  const ctaLine = `{\`${pg.ctaJsx}\`}`

  return [
    `import { Nav, ${heroImport}, WhyUs, Reviews, ServiceAreas, Contact, Footer } from "@core/web"`,
    pg.localImports,
    `import { config } from "@/lib/config"`,
    ``,
    `export default function Home() {`,
    `  return (`,
    `    <>`,
    `      <Nav config={config} scrolledTheme="light" />`,
    `      <main>`,
    `        ${heroJsx}`,
    `        ${pg.nicheSection}`,
    `        <WhyUs config={config} />`,
    `        <Reviews`,
    `          config={config}`,
    `          ctaText=${ctaLine}`,
    `        />`,
    `        <ServiceAreas config={config} />`,
    `        <Contact`,
    `          config={config}`,
    `          heading="${pg.contactHeading}"`,
    `          paragraph="${pg.contactParagraph}"`,
    `          submitText="${pg.contactSubmit}"`,
    `        />`,
    `      </main>`,
    `      <Footer config={config} />`,
    `    </>`,
    `  )`,
    `}`,
    ``,
  ].join('\n')
}

function slugify(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40)
}

const NICHE_TEMPLATE_DIR: Record<string, string> = {
  hvac: 'templates/hvac',
  roofing: 'templates/roofing',
  dentist: 'templates/dentist',
  medspa: 'templates/medspa',
  lawfirm: 'templates/lawfirm',
  remodeling: 'templates/remodeling',
  cleaning: 'templates/cleaning',
  'junk-removal': 'templates/junk-removal',
  daycare: 'templates/daycare',
  'auto-detailing': 'templates/auto-detailing',
  restaurant:          'templates/restaurant',
  'luxury-realestate': 'templates/luxury-realestate',
  'skin-clinic':       'templates/skin-clinic',
  'iv-therapy':        'templates/iv-therapy',
  'nail-studio':       'templates/nail-studio',
}

function buildDeployWorkflow(templateDir: string, projectName: string): string {
  return `name: Deploy to Cloudflare Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build --workspace=${templateDir}
      - name: Remove files exceeding CF Pages 25 MiB limit
        run: find ${templateDir}/out -size +24M -delete 2>/dev/null || true
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${templateDir}/out --project-name=${projectName} --commit-dirty=true
`
}

export async function runBuilderAgent(
  lead: Lead,
  config: PipelineConfig,
  heroImages?: HeroImages | null,
  heroVideoBuffer?: Buffer | null
): Promise<AgentResult<Lead>> {
  console.log(`[Builder] Creating repo for ${lead.name}`)

  const repoName = `site-${slugify(lead.name)}`
  const templateDir = NICHE_TEMPLATE_DIR[config.niche] || `templates/${config.niche}`
  const configPath = `${templateDir}/src/lib/config.ts`

  try {
    const repo = await createRepoFromTemplate({
      templateOwner: config.templateOwner,
      templateRepo: config.templateRepo,
      newOwner: config.deployOwner,
      newRepoName: repoName,
    })

    if (!repo) return { success: false, error: 'Failed to create repo from template' }

    const updated = await updateFile({
      owner: config.deployOwner,
      repo: repoName,
      path: configPath,
      content: lead.config_ts!,
      message: `Configure for ${lead.name}`,
    })

    if (!updated) return { success: false, error: `Failed to update ${configPath}` }

    // Generate dynamic page.tsx when hero layout is HeroCentered or HeroBento
    const heroLayoutId = lead.niche_profile?.design?.heroLayoutId ?? ''
    const pageTsx = generatePageTsx(config.niche, heroLayoutId)
    if (pageTsx) {
      const pagePath = `${templateDir}/src/app/page.tsx`
      await updateFile({
        owner: config.deployOwner,
        repo: repoName,
        path: pagePath,
        content: pageTsx,
        message: `feat: ${heroLayoutId} hero layout for ${lead.name}`,
      })
      console.log(`[Builder] page.tsx generated — ${heroLayoutId} hero ✓`)
    }

    // Inject design tokens (font + color palette) + brand color override into globals.css
    const globalsPath = `${templateDir}/src/app/globals.css`
    const designCssBlock = lead.niche_profile?.design?.cssTokenBlock
    const brandColors = lead.brand_data?.colors
    const themeMatch = lead.config_ts?.match(/theme:\s*["']([^"']+)["']/)
    const theme = themeMatch?.[1] ?? 'navy'
    const brandColorPatch = brandColors ? generateBrandColorCSS(brandColors, theme) : null

    if (designCssBlock || brandColorPatch) {
      const currentCSS = await fetchFileContent({ owner: config.deployOwner, repo: repoName, path: globalsPath })
      if (currentCSS) {
        const patch = [designCssBlock, brandColorPatch].filter(Boolean).join('\n\n')
        await updateFile({
          owner: config.deployOwner,
          repo: repoName,
          path: globalsPath,
          content: currentCSS + '\n\n' + patch,
          message: `style: inject design tokens + brand colors for ${lead.name}`,
        })
        const designInfo = lead.niche_profile?.design
        console.log(`[Builder] Design injected — ${designInfo?.personalityName ?? 'default'} | ${designInfo?.fontPairingName ?? 'default fonts'} | ${designInfo?.colorPaletteName ?? 'default colors'}`)
      }
    }

    // Upload 4 AI hero images
    if (heroImages) {
      const keys = ['hero-1', 'hero-2', 'hero-3', 'hero-4'] as const
      for (const key of keys) {
        const buf = heroImages[key]
        if (!buf) continue
        const imgOk = await uploadBinaryFile({
          owner: config.deployOwner,
          repo: repoName,
          path: `${templateDir}/public/${key}.jpg`,
          buffer: buf,
          message: `feat: AI hero image ${key}`,
        })
        if (!imgOk) console.warn(`[Builder] ${key} upload failed`)
      }
      console.log(`[Builder] Hero images uploaded`)
    }

    // Upload hero background video (luxury-realestate + any niche with video gen enabled)
    if (heroVideoBuffer) {
      const vidOk = await uploadBinaryFile({
        owner: config.deployOwner,
        repo: repoName,
        path: `${templateDir}/public/hero-bg.mp4`,
        buffer: heroVideoBuffer,
        message: 'feat: AI hero background video',
      })
      if (vidOk) {
        console.log(`[Builder] Hero video uploaded ✓`)
      } else {
        console.warn(`[Builder] Hero video upload failed`)
      }
    }

    // Add GitHub Actions workflow for Cloudflare Pages deployment (no GitHub App needed)
    const projectName = repoName
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 63)

    // Set CF secrets BEFORE pushing workflow (workflow triggers immediately on push)
    const cfToken = process.env.CLOUDFLARE_TOKEN
    const cfAccountId = process.env.CLOUDFLARE_ACCOUNT_ID
    if (cfToken && cfAccountId) {
      await Promise.all([
        setRepoSecret({ owner: config.deployOwner, repo: repoName, secretName: 'CLOUDFLARE_API_TOKEN', secretValue: cfToken }),
        setRepoSecret({ owner: config.deployOwner, repo: repoName, secretName: 'CLOUDFLARE_ACCOUNT_ID', secretValue: cfAccountId }),
      ])
      console.log(`[Builder] CF secrets set on ${repoName} ✓`)
    } else {
      console.warn('[Builder] CF creds not set — workflow will fail until secrets added manually')
    }

    // Push workflow AFTER secrets are set so first run can authenticate
    const workflowContent = buildDeployWorkflow(templateDir, projectName)
    await updateFile({
      owner: config.deployOwner,
      repo: repoName,
      path: '.github/workflows/deploy.yml',
      content: workflowContent,
      message: 'ci: Cloudflare Pages deploy via Wrangler',
    })

    return {
      success: true,
      data: {
        ...lead,
        github_repo: repo.html_url,
        status: 'built',
        // Store templateDir so deployer knows which rootDirectory to set
        brand_data: { ...lead.brand_data!, _templateDir: templateDir } as any,
      },
    }
  } catch (e: any) {
    return { success: false, error: e.message }
  }
}
